apiVersion: v1
kind: Service
metadata:
  name: front-end
  namespace: voting
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: azure-vote-front
